# https://github.com/apache/skywalking-showcase/blob/main/deploy/platform/docker/docker-compose.single-node.yaml
version: '3.8'
services:
  oap:
    image: harbor.ats.io/docker.io/apache/skywalking-oap-server:9.0.0
    container_name: oap
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
  ui-old:
    image: harbor.ats.io/docker.io/apache/skywalking-ui:8.9.1
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 18081:8080
    environment:
      SW_OAP_ADDRESS: http://oap:12800
  ui:
    image: harbor.ats.io/docker.io/apache/skywalking-ui:9.0.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 18080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800

volumes:
  data:
    driver: local
